# Generated by Django 4.0.3 on 2022-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='water', max_length=100),
            preserve_default=False,
        ),
    ]
